/// WARNING: DO NOT EDIT THIS FILE! Instead, make sure the function that calls
/// this is a SERVER COMPONENT. In other words, add "use server" on top of the file.
import 'server-only';

import { revalidateTag } from 'next/cache';
import { assertAuthenticated } from '@/auth0-hooks/server/assertAuthenticated';
import { ROCK_API_KEY, ROCK_API_URL, ROCK_FETCH_REVALIDATE_SECONDS } from '@/constants/server';
import { redactRockUrl, serverLog, truncateForLog } from '@/lib/serverLog';
import { bustRockObjectCache, readRockObjectCache, writeRockObjectCache } from '@/server-actions/internal/rockObjectCache';
import { rockClearGroupHierarchyCache } from '@/server-actions/rockGetGroupHierarchy';
import type { RockQueryParams } from '@/types/RockQueryParams';

const log = serverLog('rockFetch');

/** Build the Next.js fetch cache tag for a Rock path (e.g. `/Groups/5` → `rock:groups`) so writes can revalidate it. */
function deriveRockTag(url: string): string {
  const entity = url.split('/')[1]?.toLowerCase() || 'rock';
  return `rock:${entity}`;
}

/**
 * Single entry point for all HTTP traffic to the Rock REST API.
 *
 * Responsibilities, in order:
 *  1. Authenticate the caller (`assertAuthenticated`) — no anonymous Rock access.
 *  2. Serialize `params` into an OData query string.
 *  3. For cacheable GETs, return a hit from the Redis object cache when present.
 *  4. Issue the fetch, choosing the right Next.js cache strategy per method
 *     (tagged revalidation for GETs, `no-store` for writes).
 *  5. On success, cache GET responses; on any write, bust BOTH the Redis object
 *     cache and the Next.js Data Cache (via `revalidateTag`) plus the group
 *     hierarchy cache, so subsequent reads never return stale data.
 *
 * Prefer the `rockGet` / `rockPost` / `rockPatch` / `rockDelete` wrappers below.
 *
 * @param url      Rock API path beginning with `/` (e.g. `/Groups`).
 * @param method   HTTP verb.
 * @param params   OData query params; `undefined`/`null` values are dropped.
 * @param body     JSON body for POST/PATCH.
 * @param noCache  Skip the read cache and force `no-store` on the request.
 * @returns Parsed JSON (or `null` for empty responses / raw text if not JSON).
 * @throws If the Rock API responds with a non-OK status.
 */
export async function rockFetch(
  url: string,
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE',
  params?: RockQueryParams,
  body?: Record<string, any> | any[],
  noCache?: boolean,
  /**
   * HTTP statuses to treat as a successful no-op instead of throwing. Used to
   * make deletes idempotent: a 404 on DELETE means the entity is already gone,
   * which is the goal state — surfacing it as an error would abort otherwise
   * successful batch operations (e.g. merging duplicates against a slightly
   * stale, cached list of occurrences).
   */
  ignoreStatuses?: number[],
  skipAuthentication = false,
): Promise<any> {
  if (!skipAuthentication) {
    await assertAuthenticated();
  }

  const searchParams = new URLSearchParams();
  if (params) {
    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined && value !== null) {
        searchParams.append(key, String(value));
      }
    }
  }
  const queryString = searchParams.toString();
  const fullUrl = queryString
    ? `${ROCK_API_URL}${url}?${queryString}`
    : `${ROCK_API_URL}${url}`;

  const headers: Record<string, string> = {
    'Authorization-Token': ROCK_API_KEY,
    'Content-Type': 'application/json',
    Accept: 'application/json',
  };

  if (method === 'GET' && !noCache) {
    const cached = await readRockObjectCache(url, method, params);
    if (cached.hit) {
      return cached.value;
    }
  }

  const fetchOptions: RequestInit = { method, headers };

  if (body && (method === 'POST' || method === 'PATCH')) {
    fetchOptions.body = JSON.stringify(body);
    fetchOptions.cache = 'no-store';
  } else if (method === 'DELETE' || noCache) {
    fetchOptions.cache = 'no-store';
  } else {
    fetchOptions.next = {
      revalidate: ROCK_FETCH_REVALIDATE_SECONDS,
      tags: [deriveRockTag(url)],
    };
  }

  if (noCache) {
    fetchOptions.cache = 'no-store';
    delete (fetchOptions.next as any)?.revalidate;
  }

  // Trace GET URLs (helps debug Rock 400s from malformed OData). Gated behind
  // ROCK_DEBUG and redacted so searched contact names never reach the logs.
  if (method === 'GET') {
    log.debug('GET', redactRockUrl(fullUrl));
  }

  const response = await fetch(fullUrl, fetchOptions);
  const text = await response.text();

  if (response.ok) {
    if (!text || text.trim() === '') return null;

    let parsed: any;
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = text;
    }

    if (method === 'GET' && !noCache) {
      await writeRockObjectCache(url, method, params, parsed);
    } else if (method !== 'GET') {
      await bustRockObjectCache();
      await rockClearGroupHierarchyCache();
      // Purge the Next.js Data Cache for the mutated entity so reads (which are
      // tagged by deriveRockTag) don't return stale data on the next refetch.
      // Mirrors the Redis bust above so both server caches invalidate symmetrically.
      try {
        revalidateTag(deriveRockTag(url));
      } catch (err) {
        log.warn(`Failed to revalidateTag for ${url} during render context:`, err);
      }

    }

    return parsed;
  }

  if (ignoreStatuses?.includes(response.status)) {
    log.warn(`Ignoring ${response.status} for ${method} ${redactRockUrl(fullUrl)} (treated as no-op)`);
    return null;
  }

  // Always surface the failing request (status + redacted URL). The raw Rock
  // response body can contain names, so it is only logged when ROCK_DEBUG is on.
  log.error(response.status, method, redactRockUrl(fullUrl));
  log.debug('response body:', truncateForLog(text));

  throw new Error(`Rock API error: ${response.status} ${text}`);
}

// Convenience wrappers around `rockFetch` — these are what server actions call.
// Writes default to `noCache: true` since the response is never worth caching.

/** Cacheable GET. Pass `noCache` to bypass the read cache for always-fresh data. */
export const rockGet = (url: string, params?: RockQueryParams, noCache?: boolean) =>
  rockFetch(url, 'GET', params, undefined, noCache);

/**
 * Server-only GET for intentionally public data. Keep use narrow: callers
 * must expose only the response they have explicitly made public.
 */
export const rockGetPublic = (
  url: string,
  params?: RockQueryParams,
  noCache?: boolean,
) => rockFetch(url, 'GET', params, undefined, noCache, undefined, true);

export const rockPost = (url: string, body: any, params?: RockQueryParams, noCache: boolean = true) =>
  rockFetch(url, 'POST', params, body, noCache);

export const rockPatch = (url: string, body: any, params?: RockQueryParams, noCache: boolean = true) =>
  rockFetch(url, 'PATCH', params, body, noCache);

export const rockDelete = (
  url: string,
  params?: RockQueryParams,
  ignoreStatuses?: number[]
) => rockFetch(url, 'DELETE', params, undefined, true, ignoreStatuses);
